import json
from pathlib import Path

import pytest

from quantum_hd8 import ucnet
from quantum_hd8.client import Client, WriteNotConfirmed


class FakeSock:
    """A socket double for write tests: echoes back any PV it receives via
    sendall(), as the real daemon does within ~1 ms (measured, docs/protocol.md
    "Eco da escrita"). recv() returns b"" (simulating no more data) once the
    echo queue is drained, which Client._drain_until treats as "nothing more
    arrived" -- fast to run, no real waiting."""

    def __init__(self):
        self.tx = b""
        self._pending: list[bytes] = []

    def sendall(self, b):
        self.tx += b
        for m in ucnet.Decoder().feed(b):
            if m.code == "PV":
                path, value = ucnet.parse_pv(m)
                self._pending.append(
                    ucnet.encode("PV", ucnet.pv_payload(path, value), cbytes=b"\x69\x00\x6a\x00")
                )

    def recv(self, n):
        return self._pending.pop(0) if self._pending else b""

    def settimeout(self, t):
        pass

    def close(self):
        pass


def make_client(tmp_path) -> tuple[Client, FakeSock]:
    fake = FakeSock()
    c = Client(sock_factory=lambda *a, **k: fake)
    c.sock = fake
    c.undo_journal = tmp_path / "undo.jsonl"
    c.ranges = {"line/ch1/preampgain": {"min": 0.0, "max": 75.0, "curve": "linear"}}
    c.state = {
        "line/ch1/preampgain": 0.26,
        "line/ch1/48v": 0.0,
        "global/ledBrightness": 0.7475,
        "global/mixerMode": 0.5,
    }
    return c, fake


def test_set_linear_param_converts_human_db_to_normalized(tmp_path):
    c, _ = make_client(tmp_path)

    echoed = c.set("line/ch1/preampgain", 37.5)

    assert echoed == pytest.approx(0.5, abs=1e-4)


def test_set_records_before_after_in_undo_journal(tmp_path):
    c, _ = make_client(tmp_path)

    c.set("line/ch1/preampgain", 37.5)

    lines = c.undo_journal.read_text().splitlines()
    assert len(lines) == 1
    entry = json.loads(lines[0])
    assert entry["path"] == "line/ch1/preampgain"
    assert entry["before"] == 0.26
    assert entry["after"] == pytest.approx(0.5, abs=1e-4)


def test_set_rejects_out_of_range_linear_value(tmp_path):
    c, fake = make_client(tmp_path)

    with pytest.raises(ValueError):
        c.set("line/ch1/preampgain", 80)

    assert fake.tx == b""  # never sent -- validated before writing


def test_set_rejects_readonly_param(tmp_path):
    c, fake = make_client(tmp_path)

    with pytest.raises(PermissionError):
        c.set("line/ch1/clip", 1)

    assert fake.tx == b""


def test_set_toggle_accepts_0_or_1(tmp_path):
    c, _ = make_client(tmp_path)

    echoed = c.set("line/ch1/48v", 1)

    assert echoed == 1.0


def test_set_toggle_rejects_value_outside_0_1(tmp_path):
    c, _ = make_client(tmp_path)

    with pytest.raises(ValueError):
        c.set("line/ch1/48v", 2)


def test_set_other_curve_accepts_normalized_value(tmp_path):
    c, _ = make_client(tmp_path)
    c.ranges["line/ch1/volume"] = {"min": -96.0, "max": 10.0, "curve": "fader"}
    c.state["line/ch1/volume"] = 0.5

    echoed = c.set("line/ch1/volume", 0.8)

    assert echoed == pytest.approx(0.8, abs=1e-4)


def test_set_other_curve_rejects_value_outside_0_1(tmp_path):
    c, _ = make_client(tmp_path)
    c.ranges["line/ch1/volume"] = {"min": -96.0, "max": 10.0, "curve": "fader"}

    with pytest.raises(ValueError):
        c.set("line/ch1/volume", 1.5)


def test_set_param_without_curve_accepts_normalized_value(tmp_path):
    # global/mixerMode is type "list" with no curve at all (daemon ranges nor
    # params.json) -- falls into the normalized bucket.
    c, _ = make_client(tmp_path)

    echoed = c.set("global/mixerMode", 0.2)

    assert echoed == pytest.approx(0.2, abs=1e-4)


def test_set_linear_curve_falls_back_to_params_json_when_daemon_ranges_missing(tmp_path):
    # Fix round 1, finding 1: the daemon's Synchronize has no `ranges` entry
    # for global/ledBrightness, but the XML (params.json, regenerated by
    # tools/gen_params.py) has curve="linear", min=1, max=100 -- Client.set
    # must fall back to that instead of treating it as a bare normalized 0..1
    # write. (20 - 1) / (100 - 1) = 19/99.
    c, fake = make_client(tmp_path)
    assert "global/ledBrightness" not in c.ranges  # no daemon range known

    echoed = c.set("global/ledBrightness", 20)

    [sent] = [m for m in ucnet.Decoder().feed(fake.tx) if m.code == "PV"]
    _, sent_value = ucnet.parse_pv(sent)
    assert sent_value == pytest.approx(19 / 99, abs=1e-4)
    assert echoed == pytest.approx(19 / 99, abs=1e-4)


def test_set_linear_curve_params_json_fallback_rejects_below_min(tmp_path):
    c, _ = make_client(tmp_path)

    with pytest.raises(ValueError):
        c.set("global/ledBrightness", 0)


def test_set_linear_curve_params_json_fallback_rejects_above_max(tmp_path):
    c, _ = make_client(tmp_path)

    with pytest.raises(ValueError):
        c.set("global/ledBrightness", 101)


def test_set_unknown_path_raises_key_error(tmp_path):
    c, _ = make_client(tmp_path)

    with pytest.raises(KeyError):
        c.set("nonexistent/path", 1)


def test_set_raises_write_not_confirmed_when_no_echo_arrives(tmp_path):
    c, fake = make_client(tmp_path)
    fake.sendall = lambda b: setattr(fake, "tx", fake.tx + b)  # swallow, no echo queued

    with pytest.raises(WriteNotConfirmed):
        c.set("global/ledBrightness", 20)


def test_write_not_confirmed_has_meaningful_message(tmp_path):
    # Fix round 1, finding 2(b): bare `path` as the message left the CLI
    # printing only the path with no explanation.
    c, fake = make_client(tmp_path)
    fake.sendall = lambda b: setattr(fake, "tx", fake.tx + b)  # swallow, no echo queued

    with pytest.raises(WriteNotConfirmed) as exc_info:
        c.set("global/ledBrightness", 20)

    assert str(exc_info.value) == (
        "global/ledBrightness: o daemon não confirmou a escrita em 1 s")


def test_set_is_noop_when_toggle_already_at_requested_value(tmp_path):
    # Fix round 1, finding 2(a): measured live -- the daemon does not echo a
    # PV when the written value equals the current one, so the old code
    # always raised WriteNotConfirmed for a no-op write.
    c, fake = make_client(tmp_path)
    assert c.state["line/ch1/48v"] == 0.0

    echoed = c.set("line/ch1/48v", 0)

    assert echoed == 0.0
    assert fake.tx == b""  # nothing sent
    assert not c.undo_journal.exists()  # no undo entry


def test_set_is_noop_when_linear_int_param_quantizes_equal(tmp_path):
    # global/ledBrightness: min=1, max=100 (step 99). current state 0.7475
    # quantizes to the same integer (74) as requesting human value 75.
    c, fake = make_client(tmp_path)

    echoed = c.set("global/ledBrightness", 75)

    assert echoed == pytest.approx(0.7475, abs=1e-4)
    assert fake.tx == b""
    assert not c.undo_journal.exists()


def test_set_is_not_noop_when_linear_int_param_differs_by_a_step(tmp_path):
    c, fake = make_client(tmp_path)

    echoed = c.set("global/ledBrightness", 76)

    assert fake.tx != b""
    assert echoed == pytest.approx(75 / 99, abs=1e-4)


def test_set_is_noop_when_float_param_within_1e4_of_current(tmp_path):
    c, fake = make_client(tmp_path)
    c.ranges["line/ch1/volume"] = {"min": -96.0, "max": 10.0, "curve": "fader"}
    c.state["line/ch1/volume"] = 0.5

    echoed = c.set("line/ch1/volume", 0.5)

    assert echoed == 0.5
    assert fake.tx == b""
    assert not c.undo_journal.exists()


def test_set_list_is_noop_when_index_already_current(tmp_path):
    c, fake = make_client(tmp_path)
    c.state["global/phones1_src"] = 0.0  # index 0 of 15

    echoed = c.set_list("global/phones1_src", 0, 15)

    assert echoed == 0.0
    assert fake.tx == b""
    assert not c.undo_journal.exists()


def test_set_list_writes_when_index_differs(tmp_path):
    c, fake = make_client(tmp_path)
    c.state["global/phones1_src"] = 0.0

    echoed = c.set_list("global/phones1_src", 1, 15)

    assert fake.tx != b""
    assert echoed == pytest.approx(1 / 14, abs=1e-4)


def test_set_raw_writes_without_conversion_or_validation(tmp_path):
    c, _ = make_client(tmp_path)

    echoed = c.set_raw("line/ch1/preampgain", 0.26)

    assert echoed == pytest.approx(0.26, abs=1e-4)


# --- final review fix wave -------------------------------------------------

def test_set_ignores_stale_pv_for_same_path_and_waits_for_matching_echo(tmp_path):
    # A PV for the same path with an old value (e.g. re-sent by a scene
    # recall) arriving before the real echo must not be taken as the echo.
    c, fake = make_client(tmp_path)
    real_sendall = fake.sendall

    def sendall(b):
        fake._pending.append(ucnet.encode(
            "PV", ucnet.pv_payload("line/ch1/preampgain", 0.0), cbytes=b"\x69\x00\x6a\x00"))
        real_sendall(b)

    fake.sendall = sendall

    echoed = c.set("line/ch1/preampgain", 37.5)

    assert echoed == pytest.approx(0.5, abs=1e-4)
    assert c.state["line/ch1/preampgain"] == pytest.approx(0.5, abs=1e-4)


def test_set_raises_when_only_a_stale_pv_arrives(tmp_path):
    c, fake = make_client(tmp_path)

    def sendall(b):
        fake.tx += b
        fake._pending.append(ucnet.encode(
            "PV", ucnet.pv_payload("line/ch1/preampgain", 0.0), cbytes=b"\x69\x00\x6a\x00"))

    fake.sendall = sendall

    with pytest.raises(WriteNotConfirmed):
        c.set("line/ch1/preampgain", 37.5)


def test_set_int_param_accepts_quantized_echo(tmp_path):
    # Measured: ledBrightness 0.2 requested -> 0.202 echoed (1/99 step).
    c, fake = make_client(tmp_path)

    def sendall(b):
        fake.tx += b
        fake._pending.append(ucnet.encode(
            "PV", ucnet.pv_payload("global/ledBrightness", 19 / 99 + 0.003), cbytes=b"\x69\x00\x6a\x00"))

    fake.sendall = sendall

    # asked 20 -> 19/99; the echo is off by 0.003 (> ECHO_TOLERANCE) but in
    # the same 1/99 step, so it is the echo.
    echoed = c.set("global/ledBrightness", 20)

    assert echoed == pytest.approx(19 / 99 + 0.003, abs=1e-4)


def test_set_on_string_param_raises_clear_value_error(tmp_path):
    c, fake = make_client(tmp_path)
    c.state["line/ch1/username"] = "Guitarra"

    with pytest.raises(ValueError, match="texto"):
        c.set("line/ch1/username", 0.5)

    assert fake.tx == b""


def test_set_raw_is_noop_when_state_already_at_value(tmp_path):
    c, fake = make_client(tmp_path)

    assert c.set_raw("line/ch1/preampgain", 0.26) == 0.26
    assert fake.tx == b""


def test_set_raw_rejects_none(tmp_path):
    c, fake = make_client(tmp_path)

    with pytest.raises(ValueError):
        c.set_raw("line/ch1/preampgain", None)
    assert fake.tx == b""


def test_every_sendall_happens_under_the_send_lock(tmp_path, monkeypatch):
    import threading
    import time as _time
    from quantum_hd8 import client as client_mod

    c, fake = make_client(tmp_path)
    unlocked = []
    real_sendall = fake.sendall

    def sendall(b):
        if not c._send_lock.locked():
            unlocked.append(threading.current_thread().name)
        real_sendall(b)

    fake.sendall = sendall
    monkeypatch.setattr(client_mod, "KEEPALIVE_INTERVAL", 0.01)
    c._start_keepalive()
    c.set("line/ch1/preampgain", 37.5)
    _time.sleep(0.05)
    c.close()

    assert b"KA" in fake.tx
    assert unlocked == []
